export const cuisineList = [
    "Breakfast",
    "Burgers",
    "Pasta/Noodles",
    "Pizza",
    "Chinese",
    "Tea-Coffee",
    "Fruit Juices",
    "Tandoori Delights",
    "Noodles",
    "Chaat Specialties",
    "Flavorful Curries",
    "Biryani Bonanza",
    "Paneer Paradise",
    "Punjabi",
    "Parathas",
    "Eggclusive Delights",
    "Gujarati",
    "South Indian",
    "North Indian",
    "Sweets/Desserts",
];